import express from 'express';
import cors from 'cors';
import nodemailer from 'nodemailer';
import { fileURLToPath } from 'url';
import { dirname, join } from 'path';
import dotenv from 'dotenv';

dotenv.config();

const __filename = fileURLToPath(import.meta.url);
const __dirname = dirname(__filename);

const app = express();
app.use(cors({
  origin: process.env.FRONTEND_URL || ['http://localhost:5173', 'http://localhost:4173']
}));
app.use(express.json());

// Configure Nodemailer for Gmail
const transporter = nodemailer.createTransport({
  service: 'gmail',
  auth: {
    user: process.env.GMAIL_USER,
    pass: process.env.GMAIL_APP_PASSWORD
  }
});

app.post('/api/submit-signal', (req, res) => {
  const { type, name, email, problem, build, stage, requested_date } = req.body;
  
  // We simulate a unique ID based on timestamp since we removed SQLite
  const signalId = Date.now().toString().slice(-6);

  console.log(`Processing Signal [ ID: ${signalId} ]`);

  // Send Email Notification
  const mailOptions = {
    from: process.env.GMAIL_USER,
    to: process.env.GMAIL_USER,
    subject: `VDEV Build Signal: ${name}`,
    html: `
      <div style="font-family: 'Courier New', monospace; max-width: 600px; margin: 0 auto; background-color: #030303; border: 1px solid #333; padding: 30px; color: #fff;">
        <div style="border-bottom: 1px solid #333; padding-bottom: 20px; margin-bottom: 20px;">
          <h2 style="color: #D4AF37; margin: 0; font-size: 14px; letter-spacing: 2px; text-transform: uppercase;">VDEV // SECURE COMMS</h2>
          <p style="color: #888; font-size: 12px; margin-top: 5px;">Build Signal Received [ ID: ${signalId} ]</p>
        </div>
        
        <table style="width: 100%; border-collapse: collapse; font-size: 13px;">
          <tr>
            <td style="padding: 15px 0; border-bottom: 1px solid #222; color: #888; width: 35%; text-transform: uppercase; font-size: 11px; letter-spacing: 1px;">Initiated By</td>
            <td style="padding: 15px 0; border-bottom: 1px solid #222; color: #fff; font-weight: bold;">${name}</td>
          </tr>
          <tr>
            <td style="padding: 15px 0; border-bottom: 1px solid #222; color: #888; text-transform: uppercase; font-size: 11px; letter-spacing: 1px;">Email Identity</td>
            <td style="padding: 15px 0; border-bottom: 1px solid #222; color: #fff;"><a href="mailto:${email}" style="color: #D4AF37; text-decoration: none;">${email}</a></td>
          </tr>
          <tr>
            <td style="padding: 15px 0; border-bottom: 1px solid #222; color: #888; text-transform: uppercase; font-size: 11px; letter-spacing: 1px;">Requested Time</td>
            <td style="padding: 15px 0; border-bottom: 1px solid #222; color: #fff;">${requested_date && requested_date !== 'N/A' ? new Date(requested_date).toLocaleString() : 'As soon as possible'}</td>
          </tr>
          <tr>
            <td style="padding: 15px 0; border-bottom: 1px solid #222; color: #888; text-transform: uppercase; font-size: 11px; letter-spacing: 1px;">Current Stage</td>
            <td style="padding: 15px 0; border-bottom: 1px solid #222; color: #fff;">${stage}</td>
          </tr>
        </table>

        <div style="margin-top: 30px;">
          <h3 style="color: #888; font-size: 11px; letter-spacing: 1px; text-transform: uppercase; margin-bottom: 10px;">What Needs To Be Built</h3>
          <div style="background-color: #0A0A0A; border: 1px solid #222; padding: 15px; color: #fff; line-height: 1.5; font-family: sans-serif;">
            ${build}
          </div>
        </div>

        <div style="margin-top: 30px;">
          <h3 style="color: #888; font-size: 11px; letter-spacing: 1px; text-transform: uppercase; margin-bottom: 10px;">Problem Statement</h3>
          <div style="background-color: #0A0A0A; border: 1px solid #222; padding: 15px; color: #fff; line-height: 1.5; font-family: sans-serif;">
            ${problem}
          </div>
        </div>

        <div style="margin-top: 40px; padding-top: 20px; border-top: 1px solid #333; text-align: center; color: #555; font-size: 10px; text-transform: uppercase; letter-spacing: 1px;">
          SYSTEM GENERATED BY VDEV SIGNAL MODULE
        </div>
      </div>
    `
  };

  transporter.sendMail(mailOptions, (error, info) => {
    if (error) {
      console.error('Error sending email:', error);
      res.status(500).json({ error: 'Failed to send signal email' });
    } else {
      console.log('Email sent:', info.response);
      res.status(200).json({ success: true, id: signalId, emailSent: true });
    }
  });
});

// Endpoint to view signals - now disabled since we removed SQLite
app.get('/api/view-signals', (req, res) => {
  res.status(200).json({ message: "SQLite has been removed for serverless compatibility. All signals are securely routed via Email exclusively." });
});

// Serve static frontend files (Render Full-Stack Setup)
app.use(express.static(join(__dirname, 'dist')));

app.use((req, res) => {
  res.sendFile(join(__dirname, 'dist', 'index.html'));
});

const PORT = process.env.PORT || 3001;
app.listen(PORT, () => {
  console.log(`VDEV Signal API running on http://localhost:${PORT}`);
});
